/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "USB_CDC_1.h"
#include "USB_CDC_1_audio.h"
#include "USB_CDC_1_cdc.h"
#include "USB_CDC_1_hid.h"
#include "USB_CDC_1_midi.h"
#include "USB_CDC_1_pvt.h"
#include "USB_CDC_1_cydmac.h"
#include "USB_CDC_1_msc.h"
#include "DieTemp_1.h"
#include "DMA_Timer.h"
#include "LED_aliases.h"
#include "LED.h"
#include "Cycle_ISR_1.h"
#include "Timer_1.h"
#include "DMA_UART_Tx_dma.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "I2C_Master_1.h"
#include "I2C_Master_1_PVT.h"
#include "itg3200_int.h"
#include "ITG3200_Pin_aliases.h"
#include "ITG3200_Pin.h"
#include "USB_CDC_1_Dm_aliases.h"
#include "USB_CDC_1_Dm.h"
#include "USB_CDC_1_Dp_aliases.h"
#include "USB_CDC_1_Dp.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

